apiVersion: v1
apiVersion_info:
  description: apiVersion field
  type: string
  required: true
kind: Secret
kind_info:
  description: kind field
  type: string
  required: true
metadata:
  name: secret-tls
  name_info:
    description: name field
    type: string
    required: false
  namespace: default
  namespace_info:
    description: namespace field
    type: string
    required: false
metadata_info:
  description: metadata field
  type: object
  required: true
type: kubernetes.io/tls
type_info:
  description: type field
  type: string
  required: false
data:
  tls.crt: BASE64_ENCODED_CERT
  tls.crt_info:
    description: tls.crt field
    type: string
    required: false
  tls.key: BASE64_ENCODED_KEY
  tls.key_info:
    description: tls.key field
    type: string
    required: false
data_info:
  description: data field
  type: object
  required: false
