apiVersion: v1
apiVersion_info:
  description: apiVersion field
  type: string
  required: true
kind: Secret
kind_info:
  description: kind field
  type: string
  required: true
metadata:
  name: secret-ssh
  name_info:
    description: name field
    type: string
    required: false
  namespace: default
  namespace_info:
    description: namespace field
    type: string
    required: false
metadata_info:
  description: metadata field
  type: object
  required: true
type: kubernetes.io/ssh-auth
type_info:
  description: type field
  type: string
  required: false
data:
  ssh-privatekey: 'LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQo= # base64-encoded private
    key content

    '
  ssh-privatekey_info:
    description: ssh-privatekey field
    type: string
    required: false
data_info:
  description: data field
  type: object
  required: false
