apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 10-network-policy-allow-cidr-npc
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Fenil-Gajjar/k8s-actions-task.git
    targetRevision: main
    path: actions/10 - network-policy/allow-cidr-npc
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
