apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 12-deamonset-deamon-set
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Fenil-Gajjar/k8s-actions-task.git
    targetRevision: main
    path: actions/12 - deamonset/deamon-set
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
