apiVersion: batch/v1
kind: Job
metadata:
  name: simple-job
spec:
  template:
    spec:
      containers:
      - name: job-container
        image: busybox:latest
        command: [ "echo", "Hello from Kubernetes Job!" ]
      restartPolicy: Never
  backoffLimit: 4
