apiVersion: batch/v1 # read-only mode
kind: Job # read-only mode
metadata:
  name: batch-job # job name
  namespace: default # namespace for job execution
spec:
  activeDeadlineSeconds: 600 # overall time limit for job run (increased for scheduling delays)
  template:
    spec:
      containers:
      - name: processor
        image: python:3.9-slim # container image for the job
        command: [ "python", "-c" ] # execute python code inline
        args:
        - |
          import time
          print("Starting batch processing...")
          time.sleep(5)
          print("Batch processing completed!")
        resources:
          requests:
            memory: "256Mi" # requested memory for scheduling
            cpu: "250m" # requested CPU for scheduling
            ephemeral-storage: "1Gi"
          limits:
            memory: "512Mi" # memory limit for runtime
            cpu: "500m" # CPU limit for runtime
            ephemeral-storage: "2Gi"
      restartPolicy: OnFailure # restart pods on failure according to job policy
  backoffLimit: 2 # number of retries before marking job failed

# Title: Job - batch-job (resource-limited)
# Description: Batch job running a short Python task with resource requests/limits and an overall deadline; suitable as a resource-constrained job example.
