apiVersion: v1 # read-only mode
kind: Pod # read-only mode
# metadata: Pod identity and grouping information
metadata:
  name: onecontainer-pod # pod name
  namespace: default # namespace for the Pod
  labels:
    app: my-app # label for app identification
    environment: dev # environment label
  annotations:
    description: "My application pod" # human readable description
spec:
  restartPolicy: Always
  containers:
  - name: my-container
    image: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
    - name: ENVIRONMENT
      value: "development"
    - name: APP_PORT
      value: "80"

# Title: Pod - one-container example
# Description: Creates a single-container Pod in `default` running nginx with resource requests/limits and environment variables; suitable as a minimal app Pod example.
