apiVersion: apps/v1 # read-only mode
kind: Deployment # read-only mode
metadata:
  name: minimal-dep # deployment name
  namespace: default # namespace for this deployment
spec:
  replicas: 1 # desired replicas
  selector:
    matchLabels:
      app: minimal-dep # selector for pods managed by this deployment
  template:
    metadata:
      labels:
        app: minimal-dep # labels applied to pod template
    spec:
      containers:
      - name: my-app-container # container name
        image: nginx:latest # container image
        ports:
        - containerPort: 80 # container port exposed
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
            ephemeral-storage: "1Gi"
          limits:
            cpu: "500m"
            memory: "512Mi"
            ephemeral-storage: "2Gi"
