apiVersion: v1
apiVersion_info:
  description: apiVersion field
  type: string
  required: true
kind: Secret
kind_info:
  description: kind field
  type: string
  required: true
metadata:
  name: service-account-token
  name_info:
    description: name field
    type: string
    required: false
  namespace: default
  namespace_info:
    description: namespace field
    type: string
    required: false
  annotations:
    kubernetes.io/service-account.name: my-service-account
    kubernetes.io/service-account.name_info:
      description: kubernetes.io/service-account.name field
      type: string
      required: false
  annotations_info:
    description: annotations field
    type: object
    required: false
metadata_info:
  description: metadata field
  type: object
  required: true
type: kubernetes.io/service-account-token
type_info:
  description: type field
  type: string
  required: false
