apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 5-secrets-basic-auth
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Fenil-Gajjar/k8s-actions-task.git
    targetRevision: main
    path: actions/5 - secrets/basic-auth
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
