apiVersion: batch/v1
kind: Job
metadata:
  name: data-processing-job
spec:
  template:
    metadata:
      labels:
        app: data-processor
    spec:
      containers:
      - name: processor
        image: alpine:latest
        env:
        - name: JOB_TYPE
          value: "data-processing"
        - name: LOG_LEVEL
          value: "info"
        command: [ "sh", "-c" ]
        args:
        - |
          echo "Job Type: $JOB_TYPE"
          echo "Processing data..."
          echo "Results written to /output/results.txt"
          mkdir -p /output
          echo "Processing complete at $(date)" > /output/results.txt
        volumeMounts:
        - name: output-volume
          mountPath: /output
      volumes:
      - name: output-volume
        emptyDir: {}
      restartPolicy: Never
  backoffLimit: 3
