apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 8-resource-quota-cpu-mem
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Fenil-Gajjar/k8s-actions-task.git
    targetRevision: main
    path: actions/8 - resource-quota/resource-cpu-mem
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
