apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1-deployment-volume-dep
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Fenil-Gajjar/k8s-actions-task.git
    targetRevision: main
    path: actions/1 - deployment/volume-dep
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
