apiVersion: v1
apiVersion_info:
  description: apiVersion field
  type: string
  required: true
kind: ResourceQuota
kind_info:
  description: kind field
  type: string
  required: true
metadata:
  name: compute-quota
  name_info:
    description: name field
    type: string
    required: false
  namespace: development
  namespace_info:
    description: namespace field
    type: string
    required: false
metadata_info:
  description: metadata field
  type: object
  required: true
spec:
  hard:
    requests.cpu: '10'
    requests.cpu_info:
      description: requests.cpu field
      type: string
      required: false
    requests.memory: 20Gi
    requests.memory_info:
      description: requests.memory field
      type: string
      required: false
    limits.cpu: '20'
    limits.cpu_info:
      description: limits.cpu field
      type: string
      required: false
    limits.memory: 40Gi
    limits.memory_info:
      description: limits.memory field
      type: string
      required: false
  hard_info:
    description: hard field
    type: object
    required: false
spec_info:
  description: spec field
  type: object
  required: true
