apiVersion: v1
kind: LimitRange
metadata:
  name: pod-limits-complete
  namespace: default
spec:
  limits:
  - type: Pod
    max:
      cpu: "8"
      memory: "16Gi"
      ephemeral-storage: "10Gi"
    min:
      cpu: "200m"
      memory: "256Mi"
      ephemeral-storage: "1Gi"
