apiVersion: apps/v1 # read-only mode
kind: DaemonSet # read-only mode
metadata:
  name: example-daemonset # name of the DaemonSet
  namespace: default # namespace for the DaemonSet
  labels:
    app: example-daemon # label group for the DaemonSet
spec:
  selector:
    matchLabels:
      app: example-daemon # selector for pods managed by the DaemonSet
  template:
    metadata:
      labels:
        app: example-daemon # labels applied to each daemon pod
    spec:
      containers:
      - name: example-container
        image: nginx:latest # container image to run on each node
        ports:
        - containerPort: 80 # container port exposed by the pod
        resources:
          limits:
            memory: "512Mi" # maximum memory per pod
            cpu: "500m" # maximum CPU per pod
            ephemeral-storage: "2Gi"
          requests:
            memory: "256Mi" # resource requests for scheduling
            cpu: "250m"
            ephemeral-storage: "1Gi"
