apiVersion: v1
kind: Secret
metadata:
  name: app-credentials
  namespace: default
type: Opaque
data:
  # Values must be base64 encoded
  username: YWRtaW4= # "admin"
  password: cGFzc3dvcmQxMjM= # "password123"
stringData:
  # stringData allows plain text (will be auto-encoded)
  api-key: "my-secret-api-key-12345"
  database-url: "postgresql://user:pass@localhost:5432/db"
