apiVersion: v1 # read-only mode
kind: Service # read-only mode
metadata:
  name: my-clusterip-service # service identifier
  namespace: default # namespace for the Service
  labels:
    app: backend # label grouping
spec:
  type: ClusterIP # Service type (ClusterIP is internal access only)
  selector:
    app: backend # selects pods with these labels
    tier: api # additional selector to narrow target pods
  ports:
  - name: http # name for HTTP port
    protocol: TCP # protocol used
    port: 80 # service port exposed to clients in-cluster
    targetPort: 8080 # container port to forward traffic to
  - name: https # name for HTTPS port
    protocol: TCP
    port: 443 # service port for secure traffic
    targetPort: 8443 # container port for secure traffic
  # Title: Service - multi-port backend
  # Description: Creates a ClusterIP Service in `default` exposing HTTP and HTTPS ports and selecting backend API pods.
