apiVersion: v1
kind: Service
metadata:
  name: my-clusterip-service
  namespace: default
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
    tier: api
  ports:
  - name: http
    protocol: TCP
    port: 80 # Service port
    targetPort: 8080 # Container port
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8443
