apiVersion: v1
apiVersion_info:
  description: apiVersion field
  type: string
  required: true
kind: ServiceAccount
kind_info:
  description: kind field
  type: string
  required: true
metadata:
  name: my-service-account
  name_info:
    description: name field
    type: string
    required: false
  namespace: default
  namespace_info:
    description: namespace field
    type: string
    required: false
  labels:
    app: my-app
    app_info:
      description: app field
      type: string
      required: false
  labels_info:
    description: labels field
    type: object
    required: false
  annotations:
    description: Service account for my application
    description_info:
      description: description field
      type: string
      required: false
  annotations_info:
    description: annotations field
    type: object
    required: false
metadata_info:
  description: metadata field
  type: object
  required: true
automountServiceAccountToken: true
automountServiceAccountToken_info:
  description: automountServiceAccountToken field
  type: boolean
  required: false
