apiVersion: apps/v1 # read-only mode
kind: Deployment # read-only mode
# metadata: identifies the Deployment (name/namespace/labels)
metadata:
  name: checks-strategy-dep # deployment name
  namespace: default # namespace for the Deployment
  labels:
    app: checks-strategy-dep # label for grouping related resources
    version: v1 # version label
  annotations:
    description: "My application deployment" # deployment description
spec:
  replicas: 1 # desired number of pod replicas
  strategy:
    type: RollingUpdate # rollout strategy for updates
    rollingUpdate:
      maxSurge: 1 # additional pods allowed during rolling update
      maxUnavailable: 1 # max pods that can be unavailable during update
  selector:
    matchLabels:
      app: checks-strategy-dep
  template:
    metadata:
      labels:
        app: checks-strategy-dep
        version: v1
    spec:
      containers:
      - name: my-app-container
        image: nginx:latest
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "info"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
