apiVersion: v1 # read-only mode
kind: Pod # read-only mode
# metadata: object metadata (name/namespace/labels/annotations)
metadata:
  name: my-pod # unique Pod name
  namespace: default # namespace for the Pod
  labels:
    app: my-app # label to identify app ownership
    environment: dev # environment label (dev/staging/prod)
    version: "1.0" # version label for the Pod
  annotations:
    description: "My application pod" # human-readable description
    owner: "platform-team" # owning team or owner contact
# spec: Pod spec defines the containers, volumes and runtime behavior
spec:
  restartPolicy: Always
  serviceAccountName: default
  containers:
  - name: my-container
    image: nginx:1.25
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
      protocol: TCP
      name: http
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
    - name: ENVIRONMENT
      value: "development"
    - name: APP_PORT
      value: "80"
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
    volumeMounts:
    - name: cache-volume
      mountPath: /var/cache/nginx
    securityContext:
      runAsNonRoot: false
      allowPrivilegeEscalation: false
  volumes:
  - name: cache-volume
    emptyDir: {}
