apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
    environment: dev
    version: "1.0"
  annotations:
    description: "My application pod"
    owner: "platform-team"
spec:
  restartPolicy: Always
  serviceAccountName: default
  containers:
  - name: my-container
    image: nginx:1.25
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
      protocol: TCP
      name: http
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
    - name: ENVIRONMENT
      value: "development"
    - name: APP_PORT
      value: "80"
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
    volumeMounts:
    - name: cache-volume
      mountPath: /var/cache/nginx
    securityContext:
      runAsNonRoot: false
      allowPrivilegeEscalation: false
  volumes:
  - name: cache-volume
    emptyDir: {}
